// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const GcSchedule = __t.object("GcSchedule", {
  id: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type GcSchedule = __Infer<typeof GcSchedule>;

export const Player = __t.object("Player", {
  validAt: __t.u64(),
  dataShard: __t.u16(),
  playerId: __t.u32(),
  name: __t.string(),
  lastLoginSecs: __t.u32(),
  flags: __t.u32(),
});
export type Player = __Infer<typeof Player>;

export const PlayerIdCounter = __t.object("PlayerIdCounter", {
  id: __t.u8(),
  next: __t.u32(),
});
export type PlayerIdCounter = __Infer<typeof PlayerIdCounter>;

export const PlayerProfile = __t.object("PlayerProfile", {
  playerId: __t.u32(),
  dataShard: __t.u16(),
});
export type PlayerProfile = __Infer<typeof PlayerProfile>;

export const SequenceCounter = __t.object("SequenceCounter", {
  id: __t.u8(),
  next: __t.u16(),
});
export type SequenceCounter = __Infer<typeof SequenceCounter>;

