// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  validAt: __t.u64().primaryKey().name("valid_at"),
  cardId: __t.u32().name("card_id"),
  macroZone: __t.u64().name("macro_zone"),
  microLocation: __t.u32().name("micro_location"),
  ownerId: __t.u32().name("owner_id"),
  packedDefinition: __t.u16().name("packed_definition"),
  flagsState: __t.u32().name("flags_state"),
  flagsBk: __t.u32().name("flags_bk"),
});
