// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  timeMs: __t.u64(),
  surface: __t.u8(),
  macroZone: __t.u64(),
  q: __t.u8(),
  r: __t.u8(),
  slot: __t.u8(),
  op: __t.u8(),
  delta: __t.u8(),
};
