// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  zoneId: __t.u32(),
  timeMs: __t.u64(),
  row: __t.u8(),
  col: __t.u8(),
  defId: __t.u16(),
  stock0: __t.u8(),
  stock1: __t.u8(),
};
