// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AcquireHoldReducer from "../acquire_hold_reducer";
import AcquireLeaseReducer from "../acquire_lease_reducer";
import AddCardReducer from "../add_card_reducer";
import ClaimPendingReducer from "../claim_pending_reducer";
import CreateCardReducer from "../create_card_reducer";
import DestroyCardReducer from "../destroy_card_reducer";
import FinalizeCardReducer from "../finalize_card_reducer";
import MoveCardReducer from "../move_card_reducer";
import MoveSoulReducer from "../move_soul_reducer";
import PlaceCardReducer from "../place_card_reducer";
import ReleaseHoldReducer from "../release_hold_reducer";
import ReleasePendingReducer from "../release_pending_reducer";
import RequestBlueprintReducer from "../request_blueprint_reducer";
import SetSoulStatReducer from "../set_soul_stat_reducer";
import SpawnSoulReducer from "../spawn_soul_reducer";
import StackCardReducer from "../stack_card_reducer";
import UnlockBlueprintReducer from "../unlock_blueprint_reducer";

export type AcquireHoldParams = __Infer<typeof AcquireHoldReducer>;
export type AcquireLeaseParams = __Infer<typeof AcquireLeaseReducer>;
export type AddCardParams = __Infer<typeof AddCardReducer>;
export type ClaimPendingParams = __Infer<typeof ClaimPendingReducer>;
export type CreateCardParams = __Infer<typeof CreateCardReducer>;
export type DestroyCardParams = __Infer<typeof DestroyCardReducer>;
export type FinalizeCardParams = __Infer<typeof FinalizeCardReducer>;
export type MoveCardParams = __Infer<typeof MoveCardReducer>;
export type MoveSoulParams = __Infer<typeof MoveSoulReducer>;
export type PlaceCardParams = __Infer<typeof PlaceCardReducer>;
export type ReleaseHoldParams = __Infer<typeof ReleaseHoldReducer>;
export type ReleasePendingParams = __Infer<typeof ReleasePendingReducer>;
export type RequestBlueprintParams = __Infer<typeof RequestBlueprintReducer>;
export type SetSoulStatParams = __Infer<typeof SetSoulStatReducer>;
export type SpawnSoulParams = __Infer<typeof SpawnSoulReducer>;
export type StackCardParams = __Infer<typeof StackCardReducer>;
export type UnlockBlueprintParams = __Infer<typeof UnlockBlueprintReducer>;

