// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AcquireHoldReducer from "../acquire_hold_reducer";
import AddCardReducer from "../add_card_reducer";
import ClaimPendingReducer from "../claim_pending_reducer";
import CreateCardReducer from "../create_card_reducer";
import DestroyCardReducer from "../destroy_card_reducer";
import ReleaseHoldReducer from "../release_hold_reducer";
import ReleasePendingReducer from "../release_pending_reducer";
import SpawnSoulReducer from "../spawn_soul_reducer";

export type AcquireHoldParams = __Infer<typeof AcquireHoldReducer>;
export type AddCardParams = __Infer<typeof AddCardReducer>;
export type ClaimPendingParams = __Infer<typeof ClaimPendingReducer>;
export type CreateCardParams = __Infer<typeof CreateCardReducer>;
export type DestroyCardParams = __Infer<typeof DestroyCardReducer>;
export type ReleaseHoldParams = __Infer<typeof ReleaseHoldReducer>;
export type ReleasePendingParams = __Infer<typeof ReleasePendingReducer>;
export type SpawnSoulParams = __Infer<typeof SpawnSoulReducer>;

