// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  magneticId: __t.u64().primaryKey().name("magnetic_id"),
  anchorCardId: __t.u32().name("anchor_card_id"),
  scheduledAt: __t.scheduleAt().name("scheduled_at"),
  outerRecipeId: __t.u16().name("outer_recipe_id"),
  successRecipeId: __t.u16().name("success_recipe_id"),
  failureRecipeId: __t.u16().name("failure_recipe_id"),
  durationAt: __t.u32().name("duration_at"),
  delaySecs: __t.u32().name("delay_secs"),
  callerPlayerId: __t.u32().name("caller_player_id"),
  pulledCards: __t.array(__t.u32()).name("pulled_cards"),
});
