// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  hex: __t.u32(),
  root: __t.u32(),
  slots: __t.array(__t.u32()),
  surface: __t.u8(),
  macroZone: __t.u32(),
  microZone: __t.u8(),
  microLocation: __t.u32(),
  recipeId: __t.u16(),
};
