// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  CardStack,
} from "./types";

export default {
  get stacks() {
    return __t.array(CardStack);
  },
  root: __t.u32(),
  hex: __t.u32(),
  surface: __t.u8(),
  macroZone: __t.u32(),
  microZone: __t.u8(),
};
