// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Card = __t.object("Card", {
  validAt: __t.u64(),
  cardId: __t.u32(),
  surface: __t.u8(),
  macroZone: __t.u32(),
  microZone: __t.u8(),
  microLocation: __t.u32(),
  ownerId: __t.u32(),
  packedDefinition: __t.u16(),
  flags: __t.u8(),
});
export type Card = __Infer<typeof Card>;

export const CardStack = __t.object("CardStack", {
  root: __t.u32(),
  surface: __t.u8(),
  macroZone: __t.u32(),
  microZone: __t.u8(),
  microLocation: __t.u32(),
  stackUp: __t.array(__t.u32()),
  stackDown: __t.array(__t.u32()),
});
export type CardStack = __Infer<typeof CardStack>;

export const Player = __t.object("Player", {
  validAt: __t.u64(),
  playerId: __t.u32(),
  name: __t.string(),
  surface: __t.u8(),
  macroZone: __t.u32(),
  microZone: __t.u8(),
  microLocation: __t.u32(),
});
export type Player = __Infer<typeof Player>;

export const PlayerSession = __t.object("PlayerSession", {
  identity: __t.identity(),
  playerId: __t.u32(),
});
export type PlayerSession = __Infer<typeof PlayerSession>;

export const ScheduleDeleteCards = __t.object("ScheduleDeleteCards", {
  deleteId: __t.u64(),
  cardId: __t.u32(),
  scheduledAt: __t.scheduleAt(),
});
export type ScheduleDeleteCards = __Infer<typeof ScheduleDeleteCards>;

export const ScheduleDeletePlayers = __t.object("ScheduleDeletePlayers", {
  deleteId: __t.u64(),
  playerId: __t.u32(),
  scheduledAt: __t.scheduleAt(),
});
export type ScheduleDeletePlayers = __Infer<typeof ScheduleDeletePlayers>;

export const Zone = __t.object("Zone", {
  validAt: __t.u64(),
  zoneId: __t.u32(),
  surface: __t.u8(),
  macroZone: __t.u32(),
  packedDefinition: __t.u8(),
  t0: __t.u64(),
  t1: __t.u64(),
  t2: __t.u64(),
  t3: __t.u64(),
  t4: __t.u64(),
  t5: __t.u64(),
  t6: __t.u64(),
  t7: __t.u64(),
});
export type Zone = __Infer<typeof Zone>;

