// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AcquireCardShardReducer from "../acquire_card_shard_reducer";
import ApplyActionReducer from "../apply_action_reducer";
import ApplyActionTileReducer from "../apply_action_tile_reducer";
import ClaimPendingReducer from "../claim_pending_reducer";
import CreateCardReducer from "../create_card_reducer";
import EnsureRegionReducer from "../ensure_region_reducer";
import MoveCardsReducer from "../move_cards_reducer";
import MoveSoulReducer from "../move_soul_reducer";
import PlaceCardReducer from "../place_card_reducer";
import ReleaseCardShardReducer from "../release_card_shard_reducer";
import ReleasePendingReducer from "../release_pending_reducer";
import RequestBlueprintReducer from "../request_blueprint_reducer";
import RequestZoneReducer from "../request_zone_reducer";
import SetShardIdentityReducer from "../set_shard_identity_reducer";

export type AcquireCardShardParams = __Infer<typeof AcquireCardShardReducer>;
export type ApplyActionParams = __Infer<typeof ApplyActionReducer>;
export type ApplyActionTileParams = __Infer<typeof ApplyActionTileReducer>;
export type ClaimPendingParams = __Infer<typeof ClaimPendingReducer>;
export type CreateCardParams = __Infer<typeof CreateCardReducer>;
export type EnsureRegionParams = __Infer<typeof EnsureRegionReducer>;
export type MoveCardsParams = __Infer<typeof MoveCardsReducer>;
export type MoveSoulParams = __Infer<typeof MoveSoulReducer>;
export type PlaceCardParams = __Infer<typeof PlaceCardReducer>;
export type ReleaseCardShardParams = __Infer<typeof ReleaseCardShardReducer>;
export type ReleasePendingParams = __Infer<typeof ReleasePendingReducer>;
export type RequestBlueprintParams = __Infer<typeof RequestBlueprintReducer>;
export type RequestZoneParams = __Infer<typeof RequestZoneReducer>;
export type SetShardIdentityParams = __Infer<typeof SetShardIdentityReducer>;

