// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AttachCardToFloorReducer from "../attach_card_to_floor_reducer";
import AttachCardToHexReducer from "../attach_card_to_hex_reducer";
import BootstrapReducer from "../bootstrap_reducer";
import DebugSpawnReducer from "../debug_spawn_reducer";
import DeleteActionReducer from "../delete_action_reducer";
import DeleteCardReducer from "../delete_card_reducer";
import DeletePlayerReducer from "../delete_player_reducer";
import DeleteZoneReducer from "../delete_zone_reducer";
import DeleteZoneAtReducer from "../delete_zone_at_reducer";
import FillZoneReducer from "../fill_zone_reducer";
import FillZoneAtReducer from "../fill_zone_at_reducer";
import ResetAndBootstrapReducer from "../reset_and_bootstrap_reducer";
import SetZoneDefinitionReducer from "../set_zone_definition_reducer";
import SetZoneDefinitionAtReducer from "../set_zone_definition_at_reducer";
import SetZoneRowReducer from "../set_zone_row_reducer";
import SetZoneRowAtReducer from "../set_zone_row_at_reducer";
import SetZoneTileReducer from "../set_zone_tile_reducer";
import SetZoneTileAtReducer from "../set_zone_tile_at_reducer";
import StackCardDownReducer from "../stack_card_down_reducer";
import StackCardUpReducer from "../stack_card_up_reducer";
import UnstackCardReducer from "../unstack_card_reducer";
import UpdateCardActionIdReducer from "../update_card_action_id_reducer";
import UpdateCardDataReducer from "../update_card_data_reducer";
import UpdateCardFlagsReducer from "../update_card_flags_reducer";
import UpdateCardLocationReducer from "../update_card_location_reducer";
import UpdateCardMicroLocationReducer from "../update_card_micro_location_reducer";
import UpdateCardOwnerIdReducer from "../update_card_owner_id_reducer";
import UpdatePlayerLocationReducer from "../update_player_location_reducer";
import UpdatePlayerSoulIdReducer from "../update_player_soul_id_reducer";
import UpdatePositionReducer from "../update_position_reducer";
import UpdatePositionsReducer from "../update_positions_reducer";
import UpsertPlayerReducer from "../upsert_player_reducer";
import UpsertZoneReducer from "../upsert_zone_reducer";
import UpsertZoneAtReducer from "../upsert_zone_at_reducer";

export type AttachCardToFloorParams = __Infer<typeof AttachCardToFloorReducer>;
export type AttachCardToHexParams = __Infer<typeof AttachCardToHexReducer>;
export type BootstrapParams = __Infer<typeof BootstrapReducer>;
export type DebugSpawnParams = __Infer<typeof DebugSpawnReducer>;
export type DeleteActionParams = __Infer<typeof DeleteActionReducer>;
export type DeleteCardParams = __Infer<typeof DeleteCardReducer>;
export type DeletePlayerParams = __Infer<typeof DeletePlayerReducer>;
export type DeleteZoneParams = __Infer<typeof DeleteZoneReducer>;
export type DeleteZoneAtParams = __Infer<typeof DeleteZoneAtReducer>;
export type FillZoneParams = __Infer<typeof FillZoneReducer>;
export type FillZoneAtParams = __Infer<typeof FillZoneAtReducer>;
export type ResetAndBootstrapParams = __Infer<typeof ResetAndBootstrapReducer>;
export type SetZoneDefinitionParams = __Infer<typeof SetZoneDefinitionReducer>;
export type SetZoneDefinitionAtParams = __Infer<typeof SetZoneDefinitionAtReducer>;
export type SetZoneRowParams = __Infer<typeof SetZoneRowReducer>;
export type SetZoneRowAtParams = __Infer<typeof SetZoneRowAtReducer>;
export type SetZoneTileParams = __Infer<typeof SetZoneTileReducer>;
export type SetZoneTileAtParams = __Infer<typeof SetZoneTileAtReducer>;
export type StackCardDownParams = __Infer<typeof StackCardDownReducer>;
export type StackCardUpParams = __Infer<typeof StackCardUpReducer>;
export type UnstackCardParams = __Infer<typeof UnstackCardReducer>;
export type UpdateCardActionIdParams = __Infer<typeof UpdateCardActionIdReducer>;
export type UpdateCardDataParams = __Infer<typeof UpdateCardDataReducer>;
export type UpdateCardFlagsParams = __Infer<typeof UpdateCardFlagsReducer>;
export type UpdateCardLocationParams = __Infer<typeof UpdateCardLocationReducer>;
export type UpdateCardMicroLocationParams = __Infer<typeof UpdateCardMicroLocationReducer>;
export type UpdateCardOwnerIdParams = __Infer<typeof UpdateCardOwnerIdReducer>;
export type UpdatePlayerLocationParams = __Infer<typeof UpdatePlayerLocationReducer>;
export type UpdatePlayerSoulIdParams = __Infer<typeof UpdatePlayerSoulIdReducer>;
export type UpdatePositionParams = __Infer<typeof UpdatePositionReducer>;
export type UpdatePositionsParams = __Infer<typeof UpdatePositionsReducer>;
export type UpsertPlayerParams = __Infer<typeof UpsertPlayerReducer>;
export type UpsertZoneParams = __Infer<typeof UpsertZoneReducer>;
export type UpsertZoneAtParams = __Infer<typeof UpsertZoneAtReducer>;

