// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  nowMs: __t.u64(),
  completionMs: __t.u64(),
  boundIds: __t.array(__t.u32()),
  boundMasks: __t.byteArray(),
  destroyIds: __t.array(__t.u32()),
  createDefs: __t.array(__t.u16()),
  createSurfaces: __t.byteArray(),
  createMacroZones: __t.array(__t.u64()),
  createOwners: __t.array(__t.u32()),
  unlockTargets: __t.array(__t.u32()),
  unlockBlueprints: __t.array(__t.u16()),
  statSouls: __t.array(__t.u32()),
  statFields: __t.byteArray(),
  statBytes: __t.byteArray(),
  statDeltas: __t.array(__t.i8()),
  stockCardIds: __t.array(__t.u32()),
  stockValues: __t.array(__t.u32()),
};
