// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  nowMs: __t.u64(),
  completionMs: __t.u64(),
  surface: __t.u8(),
  macroZone: __t.u64(),
  q: __t.u8(),
  r: __t.u8(),
  holdMask: __t.u8(),
  stockSlots: __t.byteArray(),
  stockOps: __t.byteArray(),
  stockDeltas: __t.byteArray(),
};
