// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  TilePoint,
} from "./types";

export default {
  clientTimeMs: __t.u64(),
  callerPlayerId: __t.u32(),
  soulId: __t.u32(),
  soulDef: __t.u16(),
  fromQ: __t.i32(),
  fromR: __t.i32(),
  get dest() {
    return TilePoint;
  },
  departMs: __t.u64(),
  arrivalMs: __t.u64(),
};
