// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  clientTimeMs: __t.u64(),
  callerPlayerId: __t.u32(),
  cardIds: __t.array(__t.u32()),
  macroZones: __t.array(__t.u64()),
  microLocations: __t.array(__t.u32()),
  stackStates: __t.byteArray(),
};
