// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  playerId: __t.u32().primaryKey().name("player_id"),
  dataShard: __t.u16().name("data_shard"),
  lifecycleCount: __t.u32().name("lifecycle_count"),
  earliestLifecycleExpiresMs: __t.u64().name("earliest_lifecycle_expires_ms"),
});
