// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  validAt: __t.u64().primaryKey().name("valid_at"),
  macroRegion: __t.u64().name("macro_region"),
  zonePresence: __t.u64().name("zone_presence"),
  zoneAvailable: __t.u64().name("zone_available"),
  distance: __t.u16(),
});
