// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddCardReducer from "../add_card_reducer";
import BootstrapReducer from "../bootstrap_reducer";
import ClaimOrLoginReducer from "../claim_or_login_reducer";
import CreateCharacterReducer from "../create_character_reducer";
import DeployMiniZoneReducer from "../deploy_mini_zone_reducer";
import EquipCardReducer from "../equip_card_reducer";
import GenerateForestTerrainReducer from "../generate_forest_terrain_reducer";
import MoveSoulReducer from "../move_soul_reducer";
import PickupMiniZoneReducer from "../pickup_mini_zone_reducer";
import ProposeActionReducer from "../propose_action_reducer";
import SendChatMessageReducer from "../send_chat_message_reducer";
import SetLastLoginReducer from "../set_last_login_reducer";

export type AddCardParams = __Infer<typeof AddCardReducer>;
export type BootstrapParams = __Infer<typeof BootstrapReducer>;
export type ClaimOrLoginParams = __Infer<typeof ClaimOrLoginReducer>;
export type CreateCharacterParams = __Infer<typeof CreateCharacterReducer>;
export type DeployMiniZoneParams = __Infer<typeof DeployMiniZoneReducer>;
export type EquipCardParams = __Infer<typeof EquipCardReducer>;
export type GenerateForestTerrainParams = __Infer<typeof GenerateForestTerrainReducer>;
export type MoveSoulParams = __Infer<typeof MoveSoulReducer>;
export type PickupMiniZoneParams = __Infer<typeof PickupMiniZoneReducer>;
export type ProposeActionParams = __Infer<typeof ProposeActionReducer>;
export type SendChatMessageParams = __Infer<typeof SendChatMessageReducer>;
export type SetLastLoginParams = __Infer<typeof SetLastLoginReducer>;

