// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  actionId: __t.u32().primaryKey().name("action_id"),
  cardId: __t.u32().name("card_id"),
  recipe: __t.u32(),
  ownerId: __t.u32().name("owner_id"),
  layer: __t.u8(),
  macroZone: __t.u32().name("macro_zone"),
  end: __t.u32(),
  participants: __t.u8(),
});
