// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  magneticActionId: __t.u32().primaryKey().name("magnetic_action_id"),
  cardId: __t.u32().name("card_id"),
  recipe: __t.u16(),
  end: __t.u32(),
  layer: __t.u8(),
  macroZone: __t.u32().name("macro_zone"),
  loopCount: __t.u8().name("loop_count"),
  flags: __t.u8(),
  deltaT: __t.u8().name("delta_t"),
  debug: __t.u32(),
});
