// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Action = __t.object("Action", {
  actionId: __t.u32(),
  cardId: __t.u32(),
  recipe: __t.u32(),
  ownerId: __t.u32(),
  layer: __t.u8(),
  macroZone: __t.u32(),
  end: __t.u32(),
  participants: __t.u8(),
  flags: __t.u8(),
});
export type Action = __Infer<typeof Action>;

export const ActionScheduler = __t.object("ActionScheduler", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  actionId: __t.u32(),
});
export type ActionScheduler = __Infer<typeof ActionScheduler>;

export const Card = __t.object("Card", {
  cardId: __t.u32(),
  layer: __t.u8(),
  macroZone: __t.u32(),
  microZone: __t.u8(),
  microLocation: __t.u32(),
  ownerId: __t.u32(),
  packedDefinition: __t.u16(),
  flags: __t.u8(),
});
export type Card = __Infer<typeof Card>;

export const CardHold = __t.object("CardHold", {
  cardId: __t.u32(),
  actionId: __t.u32(),
});
export type CardHold = __Infer<typeof CardHold>;

export const InventoryStack = __t.object("InventoryStack", {
  root: __t.u32(),
  stackUp: __t.array(__t.u32()),
  stackDown: __t.array(__t.u32()),
});
export type InventoryStack = __Infer<typeof InventoryStack>;

export const Player = __t.object("Player", {
  playerId: __t.u32(),
  name: __t.string(),
  nameNormalized: __t.string(),
  layer: __t.u8(),
  macroZone: __t.u32(),
  microZone: __t.u8(),
  microLocation: __t.u32(),
});
export type Player = __Infer<typeof Player>;

export const PlayerSession = __t.object("PlayerSession", {
  identity: __t.identity(),
  playerId: __t.u32(),
});
export type PlayerSession = __Infer<typeof PlayerSession>;

export const Zone = __t.object("Zone", {
  macroZone: __t.u32(),
  packedDefinition: __t.u8(),
  packedDefinitionIds: __t.array(__t.u64()),
});
export type Zone = __Infer<typeof Zone>;

