// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  zoneId: __t.u32().primaryKey().name("zone_id"),
  layer: __t.u8(),
  macroZone: __t.u32().name("macro_zone"),
  packedDefinition: __t.u8().name("packed_definition"),
  t0: __t.u64().name("t_0"),
  t1: __t.u64().name("t_1"),
  t2: __t.u64().name("t_2"),
  t3: __t.u64().name("t_3"),
  t4: __t.u64().name("t_4"),
  t5: __t.u64().name("t_5"),
  t6: __t.u64().name("t_6"),
  t7: __t.u64().name("t_7"),
  deltaT: __t.u8().name("delta_t"),
});
