// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  cardId: __t.u32().primaryKey().name("card_id"),
  macroLocation: __t.u64().name("macro_location"),
  microLocation: __t.u32().name("micro_location"),
  ownerId: __t.u32().name("owner_id"),
  flags: __t.u16(),
  packedDefinition: __t.u16().name("packed_definition"),
  data: __t.u64(),
  actionId: __t.u64().name("action_id"),
});
