// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Action = __t.object("Action", {
  actionId: __t.u32(),
  cardId: __t.u32(),
  recipe: __t.u16(),
  end: __t.u32(),
  ownerId: __t.u32(),
  macroLocation: __t.u64(),
  microLocation: __t.u32(),
});
export type Action = __Infer<typeof Action>;

export const ActionScheduler = __t.object("ActionScheduler", {
  id: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  actionId: __t.u32(),
});
export type ActionScheduler = __Infer<typeof ActionScheduler>;

export const Card = __t.object("Card", {
  cardId: __t.u32(),
  macroLocation: __t.u64(),
  microLocation: __t.u32(),
  ownerId: __t.u32(),
  flags: __t.u16(),
  packedDefinition: __t.u16(),
  data: __t.u64(),
  actionId: __t.u64(),
});
export type Card = __Infer<typeof Card>;

export const Player = __t.object("Player", {
  playerId: __t.u32(),
  name: __t.string(),
  soulId: __t.u32(),
  macroLocation: __t.u64(),
  microLocation: __t.u32(),
});
export type Player = __Infer<typeof Player>;

export const Zone = __t.object("Zone", {
  macroLocation: __t.u64(),
  definition: __t.u8(),
  t0: __t.u64(),
  t1: __t.u64(),
  t2: __t.u64(),
  t3: __t.u64(),
  t4: __t.u64(),
  t5: __t.u64(),
  t6: __t.u64(),
  t7: __t.u64(),
});
export type Zone = __Infer<typeof Zone>;

