// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  cardIds: __t.array(__t.u32()),
  layers: __t.byteArray(),
  macroZones: __t.array(__t.u32()),
  microZones: __t.byteArray(),
  microLocations: __t.array(__t.u32()),
  flags: __t.array(__t.u16()),
};
