// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ChatMessage = __t.object("ChatMessage", {
  sentAt: __t.u64(),
  senderPlayerId: __t.u32(),
  senderName: __t.string(),
  body: __t.string(),
});
export type ChatMessage = __Infer<typeof ChatMessage>;

export const ChatRetention = __t.object("ChatRetention", {
  id: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type ChatRetention = __Infer<typeof ChatRetention>;

export const SequenceCounter = __t.object("SequenceCounter", {
  id: __t.u8(),
  next: __t.u16(),
});
export type SequenceCounter = __Infer<typeof SequenceCounter>;

